# Generated by Django 6.0.2 on 2026-03-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zkuser',
            name='salt',
            field=models.CharField(max_length=100),
        ),
    ]
