# Generated by Django 6.0.2 on 2026-03-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_zkuser_salt'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='zkuser',
            name='salt',
            field=models.CharField(max_length=255),
        ),
    ]
